pipeline {
    agent any

    environment {
        DOCKER_IMAGE    = 'kenmurakii/fastapi-webhook:latest'
        REMOTE_HOST     = 'kenmuraki5@34.125.27.182'
        SSH_CREDENTIALS = 'ssh_prod_instance'
    }

    stages {
        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: '089f0a8a-6638-4990-80a3-07d3c0e083e5', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USER')]) {
                    sh 'echo $DOCKERHUB_PASSWORD | docker login --username kenmurakii --password-stdin'
                }
            }
        }

        stage('Run Docker on Remote Server') {
            steps {
                script {
                    // Debug information to check if SSH Agent is working
                    sh 'echo "Debug info: ${env.SSH_AGENT_PID}"'

                    // Simplified SSH command for debugging
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'echo Hello from remote server'"
                }
                
                // Full sshagent block
                sshagent([SSH_CREDENTIALS]) {
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker stop \$(docker ps -a -q) || true'"
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker rm \$(docker ps -a -q) || true'"
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker rmi \$(docker images -q) || true'"
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker run -d --name fastapi-webhook -p 8085:80 $DOCKER_IMAGE'"
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker ps -a'"
                }
            }
        }
    }
}
